name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm i

      - run: npx bundlemon
        env:
          BUNDLEMON_PROJECT_ID: 62efc842e79e7ef2256eda7c
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
